version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ./src/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./src/mosquitto/data:/mosquitto/data
      - ./src/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    networks:
      - default
  backend:
    image: backend
    restart: always
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000
      - 8001:8001
  ml-models:
    image: ml-models
    restart: always
    build:
      context: .
      dockerfile: ./src/ml-models/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8002
      - 8003:8003
