version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
  backend:
    image: backend
    build: 
      context: .
      dockerfile: ./src/backend/Dockerfile
    environment:
       NODE_ENV: development
    ports:
       - 8000
       - 8001:8001
  ml-models:
    image: ml-models
    build: 
      context: .
      dockerfile: ./src/ml-models/Dockerfile
    environment:
       NODE_ENV: development
    ports:
       - 8002
       - 8003:8003