version: "3.9"
services:
  backend:
    image: backend
    build: 
      context: .
      dockerfile: ./src/backend/Dockerfile
    environment:
       NODE_ENV: development
    ports:
       - 8000
       - 9001:9001
  ml-models:
    image: ml-models
    build: 
      context: .
      dockerfile: ./src/ml-models/Dockerfile
    environment:
       NODE_ENV: development
    ports:
       - 8001
       - 9002:9002